from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Dict, Optional

import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

from .config import GeometryConfig

logger = logging.getLogger(__name__)


@dataclass
class GeometryResult:
    smiles: str
    mol: Optional[Chem.Mol]
    success: bool
    message: str = ""
    energy: Optional[float] = None
    conformer_id: Optional[int] = None
    xyz: Optional[str] = None
    metadata: Dict[str, float | int | str] = field(default_factory=dict)


def _mol_to_xyz(mol: Chem.Mol, conf_id: int) -> str:
    conf = mol.GetConformer(conf_id)
    symbols = [atom.GetSymbol() for atom in mol.GetAtoms()]
    coords = conf.GetPositions()
    lines = [f"{len(symbols)}", "Generated by qc.geometry"]
    for sym, (x, y, z) in zip(symbols, coords):
        lines.append(f"{sym:2s} {x:15.8f} {y:15.8f} {z:15.8f}")
    return "\n".join(lines)


def generate_3d_geometry(smiles: str, config: GeometryConfig) -> GeometryResult:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return GeometryResult(smiles=smiles, mol=None, success=False, message="RDKit failed to parse SMILES")

    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3() if config.use_etkdg else AllChem.ETKDGv2()
    if config.random_seed is not None:
        params.randomSeed = int(config.random_seed)
    params.numThreads = 0
    status = -1
    for attempt in range(max(1, config.embed_tries)):
        status = AllChem.EmbedMolecule(mol, params)
        if status == 0:
            break
    if status != 0:
        return GeometryResult(
            smiles=smiles,
            mol=None,
            success=False,
            message=f"Embedding failed (status={status})",
        )

    energy = None
    if config.optimize:
        ff_name = config.force_field.upper()
        if ff_name.startswith("MMFF"):
            props = AllChem.MMFFGetMoleculeProperties(mol, mmffVariant="MMFF94s" if "94S" in ff_name else "MMFF94")
            if props is None:
                ff_name = "UFF"
            else:
                ff = AllChem.MMFFGetMoleculeForceField(mol, props, confId=0)
                ff.Initialize()
                ff.Minimize(maxIts=config.max_iterations)
                energy = ff.CalcEnergy()
        if energy is None:
            ff = AllChem.UFFGetMoleculeForceField(mol, confId=0)
            if ff is not None:
                ff.Initialize()
                ff.Minimize(maxIts=config.max_iterations)
                energy = ff.CalcEnergy()

    conf_id = 0
    xyz = _mol_to_xyz(mol, conf_id)
    metadata = {"force_field": config.force_field, "opt_energy": energy or np.nan}
    return GeometryResult(
        smiles=smiles,
        mol=mol,
        success=True,
        message="ok",
        energy=energy,
        conformer_id=conf_id,
        xyz=xyz,
        metadata=metadata,
    )
